package org.xman.xland.core.domain;

public class Association {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_association.id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_association.sender_id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private Integer senderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_association.sender_name
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private String senderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_association.receiver_id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private Integer receiverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_association.receiver_name
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private String receiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_association.comment_id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_association.article_id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private Integer articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_association.category
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_association.memo
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_association.id
     *
     * @return the value of x_association.id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_association.id
     *
     * @param id the value for x_association.id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_association.sender_id
     *
     * @return the value of x_association.sender_id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public Integer getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_association.sender_id
     *
     * @param senderId the value for x_association.sender_id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setSenderId(Integer senderId) {
        this.senderId = senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_association.sender_name
     *
     * @return the value of x_association.sender_name
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public String getSenderName() {
        return senderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_association.sender_name
     *
     * @param senderName the value for x_association.sender_name
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setSenderName(String senderName) {
        this.senderName = senderName == null ? null : senderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_association.receiver_id
     *
     * @return the value of x_association.receiver_id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public Integer getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_association.receiver_id
     *
     * @param receiverId the value for x_association.receiver_id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setReceiverId(Integer receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_association.receiver_name
     *
     * @return the value of x_association.receiver_name
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_association.receiver_name
     *
     * @param receiverName the value for x_association.receiver_name
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_association.comment_id
     *
     * @return the value of x_association.comment_id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_association.comment_id
     *
     * @param commentId the value for x_association.comment_id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_association.article_id
     *
     * @return the value of x_association.article_id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_association.article_id
     *
     * @param articleId the value for x_association.article_id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_association.category
     *
     * @return the value of x_association.category
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_association.category
     *
     * @param category the value for x_association.category
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_association.memo
     *
     * @return the value of x_association.memo
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_association.memo
     *
     * @param memo the value for x_association.memo
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}