package org.xman.xland.core.domain;

public class Association {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_association.id
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_association.sender_id
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    private Long senderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_association.sender_name
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    private String senderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_association.receiver_id
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    private Long receiverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_association.receiver_name
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    private String receiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_association.comment_id
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    private Long commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_association.article_id
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    private Long articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_association.category
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_association.memo
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_association.id
     *
     * @return the value of x_association.id
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_association.id
     *
     * @param id the value for x_association.id
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_association.sender_id
     *
     * @return the value of x_association.sender_id
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public Long getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_association.sender_id
     *
     * @param senderId the value for x_association.sender_id
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public void setSenderId(Long senderId) {
        this.senderId = senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_association.sender_name
     *
     * @return the value of x_association.sender_name
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public String getSenderName() {
        return senderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_association.sender_name
     *
     * @param senderName the value for x_association.sender_name
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public void setSenderName(String senderName) {
        this.senderName = senderName == null ? null : senderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_association.receiver_id
     *
     * @return the value of x_association.receiver_id
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public Long getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_association.receiver_id
     *
     * @param receiverId the value for x_association.receiver_id
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public void setReceiverId(Long receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_association.receiver_name
     *
     * @return the value of x_association.receiver_name
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_association.receiver_name
     *
     * @param receiverName the value for x_association.receiver_name
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_association.comment_id
     *
     * @return the value of x_association.comment_id
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_association.comment_id
     *
     * @param commentId the value for x_association.comment_id
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_association.article_id
     *
     * @return the value of x_association.article_id
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_association.article_id
     *
     * @param articleId the value for x_association.article_id
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_association.category
     *
     * @return the value of x_association.category
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_association.category
     *
     * @param category the value for x_association.category
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_association.memo
     *
     * @return the value of x_association.memo
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_association.memo
     *
     * @param memo the value for x_association.memo
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}