package org.xman.xland.core.domain;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_category.id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_category.name
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_category.ctime
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private String ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_category.parent_id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_category.ctype
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private String ctype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_category.memo
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_category.id
     *
     * @return the value of x_category.id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_category.id
     *
     * @param id the value for x_category.id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_category.name
     *
     * @return the value of x_category.name
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_category.name
     *
     * @param name the value for x_category.name
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_category.ctime
     *
     * @return the value of x_category.ctime
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_category.ctime
     *
     * @param ctime the value for x_category.ctime
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setCtime(String ctime) {
        this.ctime = ctime == null ? null : ctime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_category.parent_id
     *
     * @return the value of x_category.parent_id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_category.parent_id
     *
     * @param parentId the value for x_category.parent_id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_category.ctype
     *
     * @return the value of x_category.ctype
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public String getCtype() {
        return ctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_category.ctype
     *
     * @param ctype the value for x_category.ctype
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setCtype(String ctype) {
        this.ctype = ctype == null ? null : ctype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_category.memo
     *
     * @return the value of x_category.memo
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_category.memo
     *
     * @param memo the value for x_category.memo
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}