package org.xman.xland.core.domain;

public class Fellow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_fellow.id
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_fellow.name
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_fellow.password
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_fellow.email
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_fellow.rtime
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    private String rtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_fellow.status
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_fellow.memo
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_fellow.id
     *
     * @return the value of x_fellow.id
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_fellow.id
     *
     * @param id the value for x_fellow.id
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_fellow.name
     *
     * @return the value of x_fellow.name
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_fellow.name
     *
     * @param name the value for x_fellow.name
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_fellow.password
     *
     * @return the value of x_fellow.password
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_fellow.password
     *
     * @param password the value for x_fellow.password
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_fellow.email
     *
     * @return the value of x_fellow.email
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_fellow.email
     *
     * @param email the value for x_fellow.email
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_fellow.rtime
     *
     * @return the value of x_fellow.rtime
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    public String getRtime() {
        return rtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_fellow.rtime
     *
     * @param rtime the value for x_fellow.rtime
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    public void setRtime(String rtime) {
        this.rtime = rtime == null ? null : rtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_fellow.status
     *
     * @return the value of x_fellow.status
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_fellow.status
     *
     * @param status the value for x_fellow.status
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_fellow.memo
     *
     * @return the value of x_fellow.memo
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_fellow.memo
     *
     * @param memo the value for x_fellow.memo
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}