package org.xman.xland.core.domain;

public class Property {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_property.id
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_property.name
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_property.type
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_property.value
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_property.id
     *
     * @return the value of x_property.id
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_property.id
     *
     * @param id the value for x_property.id
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_property.name
     *
     * @return the value of x_property.name
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_property.name
     *
     * @param name the value for x_property.name
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_property.type
     *
     * @return the value of x_property.type
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_property.type
     *
     * @param type the value for x_property.type
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_property.value
     *
     * @return the value of x_property.value
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_property.value
     *
     * @param value the value for x_property.value
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}