package org.xman.xland.core.domain;

public class Schedule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_schedule.id
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_schedule.name
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_schedule.interval
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    private String interval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_schedule.rank
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    private Long rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_schedule.memo
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_schedule.id
     *
     * @return the value of x_schedule.id
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_schedule.id
     *
     * @param id the value for x_schedule.id
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_schedule.name
     *
     * @return the value of x_schedule.name
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_schedule.name
     *
     * @param name the value for x_schedule.name
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_schedule.interval
     *
     * @return the value of x_schedule.interval
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public String getInterval() {
        return interval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_schedule.interval
     *
     * @param interval the value for x_schedule.interval
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public void setInterval(String interval) {
        this.interval = interval == null ? null : interval.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_schedule.rank
     *
     * @return the value of x_schedule.rank
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public Long getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_schedule.rank
     *
     * @param rank the value for x_schedule.rank
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public void setRank(Long rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_schedule.memo
     *
     * @return the value of x_schedule.memo
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_schedule.memo
     *
     * @param memo the value for x_schedule.memo
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}