package org.xman.xland.core.domain;

public class Score {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_score.id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_score.data_id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private Integer dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_score.name
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_score.ctime
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private String ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_score.point
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private Double point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_score.memo
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_score.id
     *
     * @return the value of x_score.id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_score.id
     *
     * @param id the value for x_score.id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_score.data_id
     *
     * @return the value of x_score.data_id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public Integer getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_score.data_id
     *
     * @param dataId the value for x_score.data_id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setDataId(Integer dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_score.name
     *
     * @return the value of x_score.name
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_score.name
     *
     * @param name the value for x_score.name
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_score.ctime
     *
     * @return the value of x_score.ctime
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_score.ctime
     *
     * @param ctime the value for x_score.ctime
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setCtime(String ctime) {
        this.ctime = ctime == null ? null : ctime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_score.point
     *
     * @return the value of x_score.point
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public Double getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_score.point
     *
     * @param point the value for x_score.point
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setPoint(Double point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_score.memo
     *
     * @return the value of x_score.memo
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_score.memo
     *
     * @param memo the value for x_score.memo
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}