package org.xman.xland.core.domain;

public class Stock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_stock.id
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_stock.name
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_stock.value
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_stock.other
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    private String other;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_stock.id
     *
     * @return the value of x_stock.id
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_stock.id
     *
     * @param id the value for x_stock.id
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_stock.name
     *
     * @return the value of x_stock.name
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_stock.name
     *
     * @param name the value for x_stock.name
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_stock.value
     *
     * @return the value of x_stock.value
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_stock.value
     *
     * @param value the value for x_stock.value
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_stock.other
     *
     * @return the value of x_stock.other
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_stock.other
     *
     * @param other the value for x_stock.other
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }
}