package org.xman.lear.domain;

public class Databook {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_databook.id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_databook.item_id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_databook.ctime
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private String ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_databook.ntime
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private String ntime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_databook.no
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private Integer no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_databook.delay
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private String delay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_databook.pause
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private Integer pause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_databook.memo
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_databook.id
     *
     * @return the value of x_databook.id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_databook.id
     *
     * @param id the value for x_databook.id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_databook.item_id
     *
     * @return the value of x_databook.item_id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_databook.item_id
     *
     * @param itemId the value for x_databook.item_id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_databook.ctime
     *
     * @return the value of x_databook.ctime
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_databook.ctime
     *
     * @param ctime the value for x_databook.ctime
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setCtime(String ctime) {
        this.ctime = ctime == null ? null : ctime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_databook.ntime
     *
     * @return the value of x_databook.ntime
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public String getNtime() {
        return ntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_databook.ntime
     *
     * @param ntime the value for x_databook.ntime
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setNtime(String ntime) {
        this.ntime = ntime == null ? null : ntime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_databook.no
     *
     * @return the value of x_databook.no
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_databook.no
     *
     * @param no the value for x_databook.no
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setNo(Integer no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_databook.delay
     *
     * @return the value of x_databook.delay
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public String getDelay() {
        return delay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_databook.delay
     *
     * @param delay the value for x_databook.delay
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setDelay(String delay) {
        this.delay = delay == null ? null : delay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_databook.pause
     *
     * @return the value of x_databook.pause
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public Integer getPause() {
        return pause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_databook.pause
     *
     * @param pause the value for x_databook.pause
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setPause(Integer pause) {
        this.pause = pause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_databook.memo
     *
     * @return the value of x_databook.memo
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_databook.memo
     *
     * @param memo the value for x_databook.memo
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}