package org.xman.lear.domain;

public class Stock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_stock.id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_stock.name
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_stock.value
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_stock.other
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    private String other;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_stock.id
     *
     * @return the value of x_stock.id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_stock.id
     *
     * @param id the value for x_stock.id
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_stock.name
     *
     * @return the value of x_stock.name
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_stock.name
     *
     * @param name the value for x_stock.name
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_stock.value
     *
     * @return the value of x_stock.value
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_stock.value
     *
     * @param value the value for x_stock.value
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_stock.other
     *
     * @return the value of x_stock.other
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_stock.other
     *
     * @param other the value for x_stock.other
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }
}