package org.xman.xland.core.persistence.res;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.xman.xland.core.domain.res.Menu;
import org.xman.xland.core.domain.res.MenuExample;

public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_menu
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    int countByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_menu
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    int deleteByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_menu
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    @Delete({
        "delete from res_menu",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_menu
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    @Insert({
        "insert into res_menu (name, path, ",
        "description, create_time, ",
        "parent_id, memo)",
        "values (#{name,jdbcType=VARCHAR}, #{path,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR}, #{createTime,jdbcType=VARCHAR}, ",
        "#{parentId,jdbcType=INTEGER}, #{memo,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="select last_insert_rowid()", keyProperty="id", before=false, resultType=Long.class)
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_menu
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_menu
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    List<Menu> selectByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_menu
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    @Select({
        "select",
        "id, name, path, description, create_time, parent_id, memo",
        "from res_menu",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Menu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_menu
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") Menu record, @Param("example") MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_menu
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    int updateByExample(@Param("record") Menu record, @Param("example") MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_menu
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_menu
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    @Update({
        "update res_menu",
        "set name = #{name,jdbcType=VARCHAR},",
          "path = #{path,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=VARCHAR},",
          "parent_id = #{parentId,jdbcType=INTEGER},",
          "memo = #{memo,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Menu record);
}