DROP TABLE IF EXISTS x_fellow;
CREATE TABLE x_fellow (
	id INTEGER NOT NULL,
	name VARCHAR(128) NULL COLLATE NOCASE,
	password VARCHAR(128) NULL,
	email VARCHAR(128) NULL COLLATE NOCASE,
	rtime DATETIME NULL,
	status VARCHAR(255) NULL,
	memo VARCHAR(255) NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS x_comment;
CREATE TABLE x_comment (
	id INTEGER NOT NULL,
	title VARCHAR(128) NULL,
	author VARCHAR(128) NULL,
	content TEXT NOT NULL,
	ctime DATETIME NULL,
	memo VARCHAR(255) NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS x_article;
CREATE TABLE x_article (
	id INTEGER NOT NULL,
	title VARCHAR(128) NULL,
	author VARCHAR(128) NULL,
	content TEXT NOT NULL,
	ctime DATETIME NULL,
	parent_id INTEGER NOT NULL  DEFAULT 0,
	memo VARCHAR(255) NULL,
	PRIMARY KEY (id)
);

INSERT INTO x_fellow(id, name) VALUES(1, 'leo');
INSERT INTO x_fellow(id, name) VALUES(2, 'yui');