package org.xman.xland.core.persistence;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.xman.xland.core.domain.Databook;
import org.xman.xland.core.domain.DatabookExample;

public interface DatabookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_databook
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    int countByExample(DatabookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_databook
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    int deleteByExample(DatabookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_databook
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    @Delete({
        "delete from x_databook",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_databook
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    @Insert({
        "insert into x_databook (item_id, ctime, ",
        "ntime, no, delay, ",
        "pause, memo)",
        "values (#{itemId,jdbcType=INTEGER}, #{ctime,jdbcType=VARCHAR}, ",
        "#{ntime,jdbcType=VARCHAR}, #{no,jdbcType=INTEGER}, #{delay,jdbcType=VARCHAR}, ",
        "#{pause,jdbcType=INTEGER}, #{memo,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="select last_insert_rowid()", keyProperty="id", before=false, resultType=Long.class)
    int insert(Databook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_databook
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    int insertSelective(Databook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_databook
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    List<Databook> selectByExample(DatabookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_databook
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    @Select({
        "select",
        "id, item_id, ctime, ntime, no, delay, pause, memo",
        "from x_databook",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Databook selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_databook
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") Databook record, @Param("example") DatabookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_databook
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    int updateByExample(@Param("record") Databook record, @Param("example") DatabookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_databook
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    int updateByPrimaryKeySelective(Databook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_databook
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    @Update({
        "update x_databook",
        "set item_id = #{itemId,jdbcType=INTEGER},",
          "ctime = #{ctime,jdbcType=VARCHAR},",
          "ntime = #{ntime,jdbcType=VARCHAR},",
          "no = #{no,jdbcType=INTEGER},",
          "delay = #{delay,jdbcType=VARCHAR},",
          "pause = #{pause,jdbcType=INTEGER},",
          "memo = #{memo,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Databook record);
}