package org.xman.xland.core.persistence;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.xman.xland.core.domain.Fellow;
import org.xman.xland.core.domain.FellowExample;

public interface FellowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_fellow
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    int countByExample(FellowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_fellow
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    int deleteByExample(FellowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_fellow
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    @Delete({
        "delete from x_fellow",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_fellow
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    @Insert({
        "insert into x_fellow (name, password, ",
        "email, rtime, status, ",
        "memo)",
        "values (#{name,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{email,jdbcType=VARCHAR}, #{rtime,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, ",
        "#{memo,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="select last_insert_rowid()", keyProperty="id", before=false, resultType=Long.class)
    int insert(Fellow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_fellow
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    int insertSelective(Fellow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_fellow
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    List<Fellow> selectByExample(FellowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_fellow
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    @Select({
        "select",
        "id, name, password, email, rtime, status, memo",
        "from x_fellow",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Fellow selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_fellow
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") Fellow record, @Param("example") FellowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_fellow
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    int updateByExample(@Param("record") Fellow record, @Param("example") FellowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_fellow
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    int updateByPrimaryKeySelective(Fellow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_fellow
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    @Update({
        "update x_fellow",
        "set name = #{name,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "rtime = #{rtime,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=VARCHAR},",
          "memo = #{memo,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Fellow record);

    /**
     * find user by id
     *
     * @param id
     * @return
     */
    Fellow findByIdXml(int id);

    /**
     * find user by name
     *
     * @param name
     * @return
     */
    Fellow findByName(String name);
}