package org.xman.xland.core.persistence;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.xman.xland.core.domain.Stock;
import org.xman.xland.core.domain.StockExample;

public interface StockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_stock
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    int countByExample(StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_stock
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    int deleteByExample(StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_stock
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    @Delete({
        "delete from x_stock",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_stock
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    @Insert({
        "insert into x_stock (name, value, ",
        "other)",
        "values (#{name,jdbcType=VARCHAR}, #{value,jdbcType=VARCHAR}, ",
        "#{other,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="select last_insert_rowid()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_stock
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    int insertSelective(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_stock
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    List<Stock> selectByExample(StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_stock
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    @Select({
        "select",
        "id, name, value, other",
        "from x_stock",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Stock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_stock
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    int updateByExampleSelective(@Param("record") Stock record, @Param("example") StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_stock
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    int updateByExample(@Param("record") Stock record, @Param("example") StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_stock
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    int updateByPrimaryKeySelective(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_stock
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    @Update({
        "update x_stock",
        "set name = #{name,jdbcType=VARCHAR},",
          "value = #{value,jdbcType=VARCHAR},",
          "other = #{other,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Stock record);
}