package org.xman.xland.core.persistence;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.xman.xland.core.domain.Word;
import org.xman.xland.core.domain.WordExample;

public interface WordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_word
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    int countByExample(WordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_word
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    int deleteByExample(WordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_word
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    @Delete({
        "delete from x_word",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_word
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    @Insert({
        "insert into x_word (text, phonetic, ",
        "trans, ctime, ltime, ",
        "count, category_id)",
        "values (#{text,jdbcType=VARCHAR}, #{phonetic,jdbcType=VARCHAR}, ",
        "#{trans,jdbcType=VARCHAR}, #{ctime,jdbcType=VARCHAR}, #{ltime,jdbcType=VARCHAR}, ",
        "#{count,jdbcType=INTEGER}, #{categoryId,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="select last_insert_rowid()", keyProperty="id", before=false, resultType=Long.class)
    int insert(Word record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_word
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    int insertSelective(Word record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_word
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    List<Word> selectByExample(WordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_word
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    @Select({
        "select",
        "id, text, phonetic, trans, ctime, ltime, count, category_id",
        "from x_word",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Word selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_word
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") Word record, @Param("example") WordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_word
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    int updateByExample(@Param("record") Word record, @Param("example") WordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_word
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    int updateByPrimaryKeySelective(Word record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_word
     *
     * @mbggenerated Sat Jun 24 15:48:18 CST 2017
     */
    @Update({
        "update x_word",
        "set text = #{text,jdbcType=VARCHAR},",
          "phonetic = #{phonetic,jdbcType=VARCHAR},",
          "trans = #{trans,jdbcType=VARCHAR},",
          "ctime = #{ctime,jdbcType=VARCHAR},",
          "ltime = #{ltime,jdbcType=VARCHAR},",
          "count = #{count,jdbcType=INTEGER},",
          "category_id = #{categoryId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Word record);
}