package org.xman.lear.persistence;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.xman.lear.domain.Association;
import org.xman.lear.domain.AssociationExample;

public interface AssociationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_association
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    int countByExample(AssociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_association
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    int deleteByExample(AssociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_association
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    @Delete({
        "delete from x_association",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_association
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    @Insert({
        "insert into x_association (sender_id, sender_name, ",
        "receiver_id, receiver_name, ",
        "comment_id, article_id, ",
        "category, memo)",
        "values (#{senderId,jdbcType=INTEGER}, #{senderName,jdbcType=VARCHAR}, ",
        "#{receiverId,jdbcType=INTEGER}, #{receiverName,jdbcType=VARCHAR}, ",
        "#{commentId,jdbcType=INTEGER}, #{articleId,jdbcType=INTEGER}, ",
        "#{category,jdbcType=VARCHAR}, #{memo,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="select last_insert_rowid()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Association record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_association
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    int insertSelective(Association record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_association
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    List<Association> selectByExample(AssociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_association
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    @Select({
        "select",
        "id, sender_id, sender_name, receiver_id, receiver_name, comment_id, article_id, ",
        "category, memo",
        "from x_association",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Association selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_association
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    int updateByExampleSelective(@Param("record") Association record, @Param("example") AssociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_association
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    int updateByExample(@Param("record") Association record, @Param("example") AssociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_association
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    int updateByPrimaryKeySelective(Association record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_association
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    @Update({
        "update x_association",
        "set sender_id = #{senderId,jdbcType=INTEGER},",
          "sender_name = #{senderName,jdbcType=VARCHAR},",
          "receiver_id = #{receiverId,jdbcType=INTEGER},",
          "receiver_name = #{receiverName,jdbcType=VARCHAR},",
          "comment_id = #{commentId,jdbcType=INTEGER},",
          "article_id = #{articleId,jdbcType=INTEGER},",
          "category = #{category,jdbcType=VARCHAR},",
          "memo = #{memo,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Association record);
}