package org.xman.lear.persistence;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.xman.lear.domain.Fellow;
import org.xman.lear.domain.FellowExample;

public interface FellowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_fellow
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    int countByExample(FellowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_fellow
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    int deleteByExample(FellowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_fellow
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    @Delete({
        "delete from x_fellow",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_fellow
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    @Insert({
        "insert into x_fellow (name, password, ",
        "email, rtime, status, ",
        "memo)",
        "values (#{name,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{email,jdbcType=VARCHAR}, #{rtime,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, ",
        "#{memo,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="select last_insert_rowid()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Fellow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_fellow
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    int insertSelective(Fellow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_fellow
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    List<Fellow> selectByExample(FellowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_fellow
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    @Select({
        "select",
        "id, name, password, email, rtime, status, memo",
        "from x_fellow",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Fellow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_fellow
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    int updateByExampleSelective(@Param("record") Fellow record, @Param("example") FellowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_fellow
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    int updateByExample(@Param("record") Fellow record, @Param("example") FellowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_fellow
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    int updateByPrimaryKeySelective(Fellow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_fellow
     *
     * @mbggenerated Sun Mar 22 21:57:22 CST 2015
     */
    @Update({
        "update x_fellow",
        "set name = #{name,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "rtime = #{rtime,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=VARCHAR},",
          "memo = #{memo,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Fellow record);

	Fellow findByIdXml(int id);
}