package org.xman.lear.persistence;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.xman.lear.domain.Score;
import org.xman.lear.domain.ScoreExample;

public interface ScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_score
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    int countByExample(ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_score
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    int deleteByExample(ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_score
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    @Delete({
        "delete from x_score",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_score
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    @Insert({
        "insert into x_score (data_id, name, ",
        "ctime, point, memo)",
        "values (#{dataId,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{ctime,jdbcType=VARCHAR}, #{point,jdbcType=FLOAT}, #{memo,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="select last_insert_rowid()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_score
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    int insertSelective(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_score
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    List<Score> selectByExample(ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_score
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    @Select({
        "select",
        "id, data_id, name, ctime, point, memo",
        "from x_score",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Score selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_score
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    int updateByExampleSelective(@Param("record") Score record, @Param("example") ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_score
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    int updateByExample(@Param("record") Score record, @Param("example") ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_score
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    int updateByPrimaryKeySelective(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_score
     *
     * @mbggenerated Tue Apr 07 17:02:42 CST 2015
     */
    @Update({
        "update x_score",
        "set data_id = #{dataId,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "ctime = #{ctime,jdbcType=VARCHAR},",
          "point = #{point,jdbcType=FLOAT},",
          "memo = #{memo,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Score record);
}